@startuml
folder Model {
  User "1" *-- "0..*" Work
  Work "1" *-- "0..*" Stage
  Stage "1" *-- "0..*" Page

  class User {
    users
    user
    name : String
    email : String
    password : String
  }

  class Work {
    works
    work
    title : String
    memo : String
    print_company : String
    due_time : Time
    target_day : Date
  }

  class Page {
    pages
    page
    status : Integer
    matter : Boolean
  }

  class Stage {
    stages
    stage
    name : String
  }
}

folder Controller {
  class UsersController {
    +index()
    +new()
    +show()
    +edit()
    +update()
  }

  class WorksController {
    +index()
    +new()
    +show()
    +edit()
    +update()
    +destroy()
  }

  class StagesController {
    +index()
    +new()
    +show()
    +edit()
    +update()
    +destroy()
  }

  class PagesController {
    +index()
    +new()
    +show()
    +edit()
    +update()
    +destroy()
  }
}

@enduml
